package in.okcredit.backend._offline.server.internal;

import com.google.gson.annotations.SerializedName;
import org.joda.time.DateTime;

public final class DueInfo {

    @SerializedName("active_date")
    public DateTime activeDate;

    @SerializedName("is_due_active")
    public boolean isDueActive;

    @SerializedName("account_id")
    public String customerId;

    @SerializedName("is_custom_date_set")
    boolean isCustomDateSet;

    @SerializedName("is_auto_generated")
    boolean isAutoGenerated;

    public DueInfo(
            DateTime activeDate,
            boolean isDueActive,
            String customerId,
            boolean isCustomDateSet,
            boolean isAutoGenerated) {
        this.activeDate = activeDate;
        this.isDueActive = isDueActive;
        this.customerId = customerId;
        this.isCustomDateSet = isCustomDateSet;
        this.isAutoGenerated = isAutoGenerated;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }

    public DateTime getActiveDate() {
        return activeDate;
    }

    public void setActiveDate(DateTime activeDate) {
        this.activeDate = activeDate;
    }

    public boolean isDueActive() {
        return isDueActive;
    }

    public void setDueActive(boolean dueActive) {
        isDueActive = dueActive;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public boolean isCustomDateSet() {
        return isCustomDateSet;
    }

    public void setCustomDateSet(boolean customDateSet) {
        isCustomDateSet = customDateSet;
    }
}
