package `in`.okcredit.backend._offline.model

import org.joda.time.DateTime

data class DueInfo(
    var customerId: String,
    var isDueActive: Boolean = false,
    var activeDate: DateTime? = null,
    var isCustomDateSet: Boolean = false,
    var isAutoGenerated: Boolean = false
)
