package `in`.okcredit.analytics

@Deprecated(message = "Use module's analytic file instead or create if not there")
object Event {

    const val BILL_ICON_CLICKED = "Bills Icon Clicked"
    const val CLICK_PROCEED_PAYMENT = "Click proceed payment"
    const val CHAT_ICON_CLICKED = "Chat Icon Clicked"
    const val CLICK_HELP_SECTION = "Click Help Section"
    const val CANCEL_DUE_DATE = "Cancel Due Date"
    const val ADD_RELATIONSHIP_FAILED = "Add Relationship Failed"
    const val UPDATE_FILTER = "Update Filter"
    const val CANCEL_FILTER = "Cancel Filter"
    const val VOICE_TRANSACTION_STARTED = "Voice Transaction Started"
    const val VOICE_TRANSACTION_CLOSED = "Voice Transaction Closed"
    const val VOICE_TRANSACTION_COMPLETED = "Voice Transaction Completed"
    const val PAGE_VIEWED = "Page Viewed"
    const val KYC_BANNER_SHOWN = "KYC banner shown"
    const val START_KYC_CLICKED = "Start KYC clicked"
    const val ENTRY_POINT_VIEWED = "Entry Point Viewed"
    const val ENTRY_POINT_CLICKED = "Entry Point Clicked"
    const val KYC_ENTRY_POINT_DISMISSED = "kyc_verification_info_dismissed"
    const val KYC_DIALOG_POPUP = "kyc_status_popup"

    const val CLEAR_FILTER = "Clear filter"
    const val SELECT_FILTER = "Select Filter"
    const val SELECT_DUE_DATE = "Select Due Date"
    const val DUE_DATE_CONFIRMED = "Due Date Confirmed"
    const val CLEAR_DUE_DATE = "Clear Due Date"
    const val FAILURE = "Failure"
    const val RX_ERRORHANDLER = "Rx ErrorHandler"

    const val REQUEST_OTP = "Request OTP"

    // Supplier Credit
    const val SUBMIT_FEEBBACK = "Submit Feedback"
    const val VIEW_RELATIONSHIP = "View Relationship"
    const val VIEW_COMMON_LEDGER = "View Common Ledger"
    const val SEARCH_RELATIONSHIP = "Search Relationship"
    const val ADD_RELATIONSHIP = "Add Relationship"
    const val CALL_RELATIONSHIP = "Call Relationship"
    const val SEND_REMINDER = "Send Reminder"
    const val IMPORT_CONTACT = "Import Contact"
    const val REFRESH = "Refresh"
    const val VIEW_DRAWER = "View Drawer"
    const val ADD_TRANSACTION_STARTED = "Add Transaction Started"
    const val ADD_RELATIONSHIP_STARTED = "Add Relationship Started"
    const val ADD_RELATIONSHIP_SUCCESS = "Add Relationship Success"
    const val VIEW_TRANSACTION = "View Transaction"
    const val VIEW_DISCOUNT = "View Discount"
    const val VIEW_PROFILE = "View Profile"
    const val VIEW_ACCOUNT = "View Account"
    const val VIEW_REWARDS = "View Rewards"
    const val VIEW_PRIVACY = "View Privacy"
    const val VIEW_MENU_REMINDER = "View Menu Reminder"
    const val CALL = "Call"
    const val VIEW_HELP = "View Help"
    const val VIEW_HELP_ITEM = "View Help Item"
    const val VIEW_HELP_TOPIC = "View Help Topic"

    const val SHARE_APP = "Share App"
    const val UPDATE_PPROFILE = "Update Profile"
    const val SEARCH_CATEGORY = "Search Category"
    const val SELECT_PROFILE = "Select Profile"
    const val CONTACT_OKCREDIT = "Contact Okcredit"
    const val VIEW_LANGUAGE = "View Language"
    const val SELECT_LANGUAGE = "Select Language"
    const val SHARE_BUSINESS_CARD = "Share Business Card"
    const val DELETE_RELATIONSHIP = "Delete Relationship"
    const val YOUTUBE_VIDEO = "Youtube Video"
    const val SEND_REPORT = "Send Report"
    const val IN_APP_NOTI_DISPLAYED = "InAppNotification Displayed"
    const val IN_APP_REVIEW_VIEWED = "In app review viewed"
    const val IN_APP_REVIEW_DONE = "In app review done"
    const val IN_APP_NOTI_CLICKED = "InAppNotification Clicked"
    const val SUBMIT_FEEDBACK = "Submit Feedback"
    const val SELECT_RATING = "Select Rating"
    const val IN_APP_NOTI_CLEARED = "InAppNotification Cleared"
    const val IDENTIFIED_CATEGORY_MOBILE = "Identified Category Mobile"
    const val IDENTIFIED_CATEGORY_B2B = "Identified Category B2b"
    const val DELETE_TRANSACTION = "Delete Transaction"
    const val DELETE_DISCOUNT = "Delete Discount"
    const val REMINDER_LONG_PRESS = "Reminder Long Press"
    const val SELECT_REMINDER_SETTING = "Select Reminder Setting"
    const val DELETE_RECEIPT = "Delete Receipt"
    const val ADD_NOTE_STARTED = "Add Note Started"
    const val ADD_RECEIPT_STARTED = "Add Receipt Started"
    const val ADD_NOTE_COMPLETED = "Add Note Completed"
    const val ADD_NOTE_CLICKED = "Add Note Clicked"
    const val EDIT_RECEIPT = "Edit Receipt"
    const val ADD_RECEIPT_COMPLETED = "Add Receipt Completed"
    const val TRANSACTION_FILTER_POPUP_SHOWN = "Transaction Filter Popup Shown"
    const val TRANSACTION_FILTER_TYPE_SELECTED = "Transaction Filter type Selected"
    const val SELECT_NAME = "Select Name"
    const val CONFIRM_NAME = "Confirm Name"
    const val VIEW_CONTACT_PERMISSION = "View Contact Permission"
    const val IMPORT_CONTACT_CLICKED = "Import Contact Clicked"
    const val BLOCK_RELATION_CLICKED = "Block Relation Clicked"
    const val UNBLOCK_RELATION_CLICKED = "Unblock Relation Clicked"
    const val BLOCK_RELATION = "Block Relation"
    const val UNBLOCK_RELATION = "Unblock Relation"
    const val LOAD_PAYMENT_DESTINATION = "Load Payment Destination"
    const val ACCOUNT_REPORT_CLICK = "acct_report_click"
    const val ACCOUNT_EDIT_AMOUNT_DOT_DISPLAYED = "acct_edit_amount_dot_displayed"
    const val ACCOUNT_EDIT_AMOUNT_CLICK = "acct_edit_amount_click"
    const val ACCOUNT_EDIT_AMOUNT_ENTERED = "acct_edit_amount_entered"
    const val ACCOUNT_EDIT_AMOUNT_CONFIRMED = "acct_edit_amount_confirm"
    const val ACCOUNT_EDIT_AMOUNT_HISTORY_VIEW = "acct_edit_amount_history_view"
    const val ACCOUNT_EDIT_AMOUNT_HISTORY_CLOSE = "acct_edit_amount_history_close"
    const val ACCOUNT_EDIT_AMOUNT_INFO_CLICK = "acct_restricted_info_click"
    const val ACCOUNT_EDIT_AMOUNT_POPUP = "acct_edit_amount_popup"
    const val ACCOUNT_DELETE_CLICK = "acct_delete_click"

    // Collection
    const val STARTED_ADOPT_COLLECTION = "Started Adopt Collection"
    const val STARTED_COLLECTION_ADAPTION_TYPE = "Selected Collection Adoption Type"
    const val INVALID_BANK_DETAILS = "Invalid Bank Details"
    const val COLLECTION_BULK_REMINDER = "Collection Bulk Reminder"
    const val VIEW_COLLECTION_BULK = "View Collection Bulk"
    const val COLLECTION_ADAPTION_COMPLETED = "Collection Adoption Completed"
    const val VIEW_COLLECTION_MAIN = "View Collection Main"
    const val VIEW_COLLECTION_PROFILE = "View Collection Profile"
    const val SEND_COLLECTION_REMINDER = "Send Collection Reminder"
    const val VIEW_QR = "View QR"
    const val CONFIRM_MOBILE_CHANGE = "Confirm Mobile Change"
    const val VIEW_LIVESALES_QR = "View Live Sale QR"
    const val VIEW_LIVESALES = "View Live Sales"
    const val STOP_LIVESALE_QR = "Stop Live Sale QR"
    const val CLICKED_ON_DATE_SELECTION = "Clicked on Date Selection"
    const val CLICKED_ON_TODAY = "Clicked on Today"
    const val CLICKED_ON_YESTERDAY = "Clicked on Yesterday"
    const val CLICKED_ON_LAST_SEVEN_DAYS = "Clicked on Last 7 Days"
    const val CLICKED_ON_LAST_THIRTY_DAYS = "Clicked on Month"
    const val CLICKED_ON_SHARE_LINK_PAY = "Clicked on share link pay"
    const val CLICKED_ON_LINK_PAY_ICON = "Clicked on link pay icon"
    const val CLICKED_INSURANCE = "Clicked Insurance"
    const val CONFIRM_COLLECTION_DETAILS = "Confirm Collection Details"
    const val ENTERED_INVALID_COLLECTION_DETAILS = "Entered Invalid Collection Details"
    const val ONLINE_TRANSACTION_ID = "Online Transaction Id"
    const val ONLINE_PAYMENT_TO = "Online Payment To"
    const val ADDED_BY = "Added By"
    const val PAYMENT_FAILED_CLICK = "Payment Failed Click"
    const val COLLECTION_INAPP_DISPLAYED = "Collection InApp Displayed"

    // Debug Events
    const val FILE_UPLOAD_ERROR = "FileUpload: Error"
    const val SYNC_ERROR = "Sync: Error"
    const val SYNC_STARTED = "Sync: Started"
    const val SYNC_COMPLETED = "Sync: Completed"
    const val SYNC_RESTART = "Sync: Restart"
    const val DEBUG = "Debug"
    const val SYNC_DIRTY_TRANSACTION = "Sync Dirty Transaction"

    // Login
    const val VERIFY_MOBILE = "Verify Mobile"
    const val SELECT_MOBILE = "Select Mobile"
    const val LOGIN_SUCCESS = "Login Success"
    const val REGISTER_SUCCESSFUL = "Register: Successful"

    // Share
    const val SHARED = "Shared"
    const val SHARED_ON_WHATSAPP_CLICK = "ShareScreen: Share On Whatsapp Clicked"
    const val APK_SHARED_ON_WHATSAPP_CLICK = "ShareScreen: APK Share On Whatsapp Clicked"

    // AppLock
    const val APP_LOCK_ENABLED = "AppLock Enabled"
    const val APP_LOCK_DISABLED = "AppLock Disabled"
    const val SECURITY_SCREEN_APP_LOCK_ENABLE_CLICKCED = "Security Screen: AppLock clicked"
    const val DEVICE_LOCK_SETTING = "Redirect to DeviceSettings"
    const val APPLOCK_CARD_DISPAYED = "AppLock Card Displayed"
    const val APPLOCK_CARD_CLICKED = "AppLock Card Clicked"
    const val APPLOCK_CROSS_ICON_CLICKED = "AppLock Cross Icon Clicked"

    // Transaction details
    const val AMOUNT_CLICKED = "Amount clicked"
    const val ADDED_ON = "Added On"
    const val DATE_CLICKED = "Date Clicked"
    const val COMMUNICATION_DELIVERED = "Communication Delivered"
    const val SYNC_CLICKED = "Sync Clicked"
    const val REWARD_SCREEN = "Reward Screen"
    const val PAYMENT_RESULT_SCREEN = "Payment Result Screen"
    const val SETUP_COLLECTION_CLICKED = "Setup Collection Clicked"
    const val REWARD_CLAIMED_SCREEN = "Reward Claimed Screen"
    const val BACK_CLICKED = "Back Clicked"
    const val TXN_DETAILS_TRACK = "Transaction Details Track"

    // Home
    const val PROFILE_ICON_CLICKED = "Profile Icon Clicked"
    const val PROFILE_POP_UP_DISPLAYED = "Profile Pop Up Displayed"

    const val VIEW_CALENDER_PERMISSION = "View Calender Permission"

    const val DENY_PERMISSION = "Deny Permission"

    const val ADD_DISCOUNT_STARTED = "Add Discount Started"

    const val ADD_DISCOUNT_COMPLETED = "Add Discount Completed"
    const val VIEW_MORE_CLICK = "View More Click"

    const val RELATIONSHIP_MIGRATION_STARTED = "Relationship Migration Started"
    const val ALLOW_RELATIONSHIP_MIGRATION = "Allow Relationship Migration "
    const val CONFIRM_RELATIONSHIP_MIGRATION = "Confirm Relationship Migration"
    const val CANCEL_RELATIONSHIP_MIGRATION = "Cancel Relationship Migration"
    const val RELATION_MIGRATION_SUCCESS = "Relationship Migration Success"
    const val RELATION_MIGRATION_FAILED = "Relationship Migration Failed"
    const val RETRY_MIGRATION = "Retry Migration"
    const val GRANT_PERMISSION = "Grant Permission"

    // Link Pay Events
    const val VIEW_LINK_PAY = "View LinkPay"
    const val VIEW_LINK_PAY_QR = "View LinkPay QR"
    const val LINK_PAY_QR_CLOSED = "LinkPay QR Closed"
    const val SHARE_LINK_PAY = "Share LinkPay"
    const val CHANGE_COLLECTION_METHOD = "Change Collection Method"
    const val ENTER_COLLECTION_DETAILS = "Enter Collection Details"

    // Supplier Payment Events
    const val ONLINE_PAYMENT_CLICK = "Online Payment Click"
    const val CHANGE_PAYMENT_DETAILS = "Change Payment Details"

    // Expense
    const val ADD_EXPENSE_STARTED = "Add Expense Started"
    const val EXPENSE_AMOUNT_ENTERED = "Expense Amount Entered"
    const val ADD_EXPENSE_COMPLETED = "Add Expense Completed"
    const val SELECT_EXPENSE_DATE = "Select Expense Date"
    const val EXPENSE_DATE_UPDATED = "Expense Date Updated"
    const val ADD_EXPENSE_TYPE_STARTED = "Add Expense Type Started"
    const val SUGGESTION_CLICK = "Suggestion Click"
    const val ADD_EXPENSE_TYPE_COMPLETED = "Add Expense Type Completed"
    const val VIEW_EXPENSE = "View Expense"
    const val UPDATE_DATE_RANGE = "Update Date Range"
    const val VIEW_CALENDAR = "View Calender"
    const val CLEAR_CALENDAR = "Clear Calender"
    const val EXPENSE_LONG_PRESS = "Expense Long Press"
    const val DELETE_EXPENSE_CLICK = "Delete Expense Click"
    const val DELETE_EXPENSE_CANCELLED = "Delete  Expense Cancelled"
    const val EXPENSE_AUDIO_TUTORIAL_CANCEL = "Expense Audio Tutorial Cancel"
    const val EXPENSE_FEEDBACK_CLICKED = "Expense Feedback Clicked"
    const val EXPENSE_FEEDBACK_SUBMIT = "Expense Feedback Submit"
    const val EXPENSE_LOADED = "Expense Loaded"
    const val SELECT_DATE_RANGE = "Select Date Range"

    const val UPDATE_CASH_SALE_DATE = "Update Cash Sale Date"
    const val UPDATE_CASH_SALE_DATE_RANGE = "Update Cash Sale Date Range"
    const val VIEW_CASH_SALE_TRANSACTION = "View Cash Sale Transaction"
    const val DISPLAY_DATE_CLICK = "Display Date Click"
    const val DELETE_CASH_SALE_CLICK = "Delete Cash Sale Click"
    const val CASH_SALE_DELETED = "Cash Sale Deleted"
    const val DELETE_CASH_SALE_CANCELLED = "Delete Cash Sale Cancelled"
    const val ADD_CASH_SALE_STARTED = "Add Cash Sale Started"
    const val CASH_SALE_AMOUNT_ENTERED = "Cash Sale Amount Entered"
    const val ADD_CASH_SALE_COMPLETED = "Add Cash Sale Completed"
    const val SELECT_CASH_SALE_DATE = "Select Cash Sale Date"
    const val ADD_CASH_SALE_ITEM_COMPLETED = "Add Cash Sale Item Completed"
    const val CASH_SALE_TRANSACTION_LONGPRESS = "Cash Sale Transaction Longpress"

    const val FCM_NOTIFICATION_RECEIVED = "FCM Notification Received"
    const val SYNC_TRANSACTIONS_SUCCESSFUL = "Sync Transactions Successful"
    const val CLEARED = "Cleared"
    const val SUPPLIER_SYNC_TXN_SUCCESSFUL = "supplier_sync_txn_successful"

    // Experiment SMS
    const val CLICKED_NOT_NOW = "Clicked NotNow"
    const val CLICKED_TELL_NOW = "Clicked TellNow"

    const val BREADCRUMB = "Breadcrumb"

    const val PAY_ONLINE_PAGE_VIEW = "Pay Online Page View"
    const val PAY_ONLINE_CASHBACK_PAGE_VIEW = "Pay Online Cashback Page View"
    const val ENTER_AMOUNT_CASHBACK_PAGE_VIEW = "Enter Amount Cashback Page View"
    const val PAYMENT_REWARD_STATUS_PAGE_VIEW = "Payment Reward Status Page View"
    const val PAYMENT_STATUS_REWARD_ICON_CLICKED = "Payment Status Reward Icon Clicked"

    const val PERMISSION_GRANTED = "Permission Granted"
    const val PERMISSION_DENIED = "Permission Denied"
}

object PropertyKey {
    const val DATE_RANGE = "date_range"
    const val BILL = "Bill"
    const val LIST = "List"
    const val SEARCH = "Search"
    const val Item = "Item"
    const val TYPE = "Type"
    const val ALWAYS = "Always"
    const val REASON = "Reason"
    const val FIELD = "Field"
    const val CATEGORY_ID = "Category ID"
    const val BUSINESS_TYPE_ID = "Business ID"
    const val GPS = "GPS"
    const val SCREEN = "Screen"
    const val ALL = "All"
    const val SORT_BY = "Sort By"
    const val RELATION = "Relation"
    const val TARGET = "Target"
    const val MIGRATING_RELATION = "Migrating Relation"
    const val DUE_AMOUNT = "Due Amount"
    const val DUE_RANGE = "Due Range"
    const val PAYMENT = "Payment"
    const val CREDIT = "Credit"
    const val SET_VALUE = "Set Value"
    const val DEFAULT = "Default"
    const val ORIGIN_VALUE = "Origin Value"
    const val VIDEO_ID = "Video Id"
    const val ERROR = "Error"
    const val ACTION = "Action"
    const val METHOD = "Method"
    const val REMOVED = "Removed"
    const val SOURCE = "Source"
    const val CUSTOMER_ID = "Customer_id"
    const val ACCOUNT_ID = "account_id"
    const val TXN_ID = "Transaction_id"
    const val NOTE = "Note"
    const val LOCAL_TXN_ID = "local_transaction_id"
    const val FEEDBACK = "Feedback"
    const val VALUE = "Value"
    const val IS_EDIT = "IS Edit"
    const val SHOW_IMAGE = "Show Image"
    const val FLOW = "Flow"
    const val DATE_TYPE = "date_type"
    const val COUNT = "Count"
    const val BLOCKED = "Blocked"
    const val SERVICE = "Service"
    const val DESTINATION = "Destination"
    const val AB_VARIANT = "AB Variant"
    const val SELECT_ALL = "Select All"
    const val SEND_COUNT = "Send Count"
    const val TOTAL_COUNT = "Total Count"
    const val TIMESTAMP = "Timestamp"
    const val IS_FILE = "Is File"
    const val FOCAL_AREA = "Focal Area"
    const val ENABLED = "Enabled"
    const val REGISTER = "Register"
    const val BALANCE = "Balance"
    const val STATUS = "Status"
    const val REWARD_AMOUNT = "Reward Amount"
    const val REWARD_ID = "Reward Id"
    const val REWARD_VALUE = "Reward Value" // alternate of amount
    const val REWARD_STATUS = "Reward Status"
    const val COLLECTION_ADOPTED = "Collection Adopted"

    // share
    const val CONTENT = "content"
    const val PLATFORM = "platform"
    const val PACKAGE_ID = "package_id"
    const val SHARE_TYPE = "share_type"

    // Transaction details
    const val CHANNEL = "Channel"

    // help section
    const val INTERACTION = "Interaction"
    const val FORMAT = "Format"

    const val VERSION = "Version"
    const val VIDEO_TYPE = "Video Type"

    const val COLLECTION_CAMPAIGN = "Collection Campaign"
    const val SUPPLIER_LIST = "Supplier List"
    const val POSITION = "Position"
    const val UNREAD_COUNT = "Unread Count"
    const val OLD_AMOUNT = "Old Amount"
    const val AMOUNT = "Amount"
    const val BillDate = "BillDate"

    // Cashback
    const val CASHBACK_MESSAGE_TYPE = "Cashback Message type"
    const val CASHBACK_AMOUNT = "Cashback value"
    const val MINIMUM_PAYMENT_AMOUNT = "Min Transaction Value"

    // Kyc
    const val KYC_MESSAGE_TYPE = "kyc_message_type"
    const val RISK_TYPE = "risk_type"
    const val DAILY_LIMIT_LEFT = "daily_limit_left"

    const val COMMON_LEDGER = "Common ledger"
    const val ENTRY = "ENTRY"
    const val CASHBACK_MSG_SHOWN = "cashback_message_shown"
    const val CASHBACK_DUE_AMOUNT = "due_amount"
}

object PropertyValue {
    const val RELATIONSHIP_SCREEN = "Relationship Screen"
    const val CUSTOMER_FILTER = "Customer Filter "
    const val NATIVE = " Native"
    const val SUPPLIER_TAB = " Supplier Tab"
    const val ALL = "All"
    const val NEW = "New"
    const val OLD = "Old"
    const val DEEPLINK = "Deeplink"
    const val EXISTING_NUMBER = "Existing Number"
    const val NUMBER_CHANGE = "Number Change"
    const val TRUE = "true"
    const val FALSE = "false"
    const val CUSTOMER = "Customer"
    const val SUPPLIER = "Supplier"
    const val HOME_PAGE = "Homepage"
    const val COMMON_LEDGER = "Common Ledger"
    const val CONTACT = "Contact"
    const val SEARCH_CONTACT = "Search Contact"
    const val RELATION_PAGE = "Relation Page"
    const val MERCHANT = "Merchant"
    const val HOME_PAGE_SCREEN = "Home page"
    const val MERCHANT_SCREEN = "Merchant Screen"
    const val HELP_SCREEN = "Help Screen"
    const val WHATSAPP = "Whatsapp"
    const val ADD_CUSTOMER = "Add Customer"
    const val ADD_SUPPLIER = "Add Supplier"
    const val SHARE = "Share"
    const val AMOUNT = "Amount"
    const val CLICK = "Click"
    const val DRAWER = "Drawer"
    const val FAB = "Fab"
    const val Account_Statement = "Account Statement"
    const val ADD_CLICKED = "Add Clicked"
    const val STARTED = "Started"
    const val ENDED = "Ended"
    const val FAIL = "Fail"
    const val EMAIL = "Email"
    const val NAME = "Name"
    const val ABOUT = "About"
    const val PERSONAL_NAME = "Personal Name"
    const val CATEGORY = "Category"
    const val BUSINESS_TYPE = "Business Type"
    const val ADDRESS = "Address"
    const val MOBILE = "Mobile"
    const val TX_PERMISSION = "Tx Permission"
    const val DUE_DATE = "Due Date"
    const val OLD_DUE_DATE = "Old Due Date"
    const val REMINDER_SETTING = "Reminder Setting"
    const val SMS = "SMS"
    const val SMS_SETTINS = "SMS Settings"
    const val SMS_LANG = "SMS Lang"
    const val CUSTOMER_PERMISSION = "Customer Permission"
    const val GALLERY = "Gallery"
    const val CAMERA = "Camera"
    const val PHOTO = "Photo"
    const val VIEW = "View"
    const val CUSTOMER_SCREEN = "customer_screen"
    const val SUPPLIER_SCREEN = "supplier_screen"
    const val LOCATION = "Location"
    const val STORAGE = "Storage"
    const val TRANSACTION = "Transaction"
    const val MAP_SERVER_ERROR = "Map Server Error"
    const val AUTH_ERROR = "Auth Error"
    const val REASON = "Reason"
    const val CAUSE = "Cause"
    const val STACKTRACE = "StackTrace"
    const val IMAGE_WRITE_FAILED = "Remainder Image Write Failed"
    const val WHATS_APP_ERROR = "Whatsapp Error"
    const val MOBILE_COFLICT = "Mobile Conflict"
    const val CYCLIC_ACCOUNT = "Cyclic Account"
    const val ADD_TXN = "Add Transaction"
    const val OTHER = "Other"
    const val INVALID_ADDRESS = "Invalid Address"
    const val LOGIN = "Login"
    const val BACKPRESSED = "Backpress"
    const val REMINDER_RELATION_PAGE = "Reminder Relation Page"
    const val APP_LOCK = "AppLock"
    const val ENABLE = "Enable"
    const val DISABLE = "Disable"
    const val UPI = "Upi"
    const val BANK = "Bank"
    const val MERCHANT_PROFILE = "merchant_profile"
    const val MERCHANT_ADDRESS = "merchant_address"
    const val ALL_TRANSACTIONS = "All Transactions"
    const val ONLINE_TRANSACTIONS = "Online Transactions"
    const val SETTINGS = "Settings"
    const val RELAUNCH = "Relaunch"
    const val MERCHANT_DESTINATION_INSIGHT_V2 = "Merchant Destination InsightV2"
    const val ACCOUNT_NUMBER = "Account Number"
    const val IFSC = "IFSC"
    const val Typing = "Typing"
    const val LINK_PAY = "LinkPay"
    const val EDIT_TRANSACTION = "Edit Transaction"
    const val PAYMENT = "Payment"
    const val CREDIT = "Credit"
    const val DELETED = "Deleted"
    const val EDITED = "Edited"
    const val ONLINE_PAYMENT = "Online Payment"
    const val ONLINE_TRANSACTION = "Online Transaction"
    const val PROCESSING = "Processing"
    const val MENU_ITEM = "Menu Item"

    const val GO_TO_REWARDS_CTA_TEXT = "Go to Rewards"
    const val TELL_YOUR_FRIENDS_CTA_TEXT = "Refer"
    const val ENTER_BANK_DETAILS_CTA_TEXT = "Enter destination"

    const val TRANSACTION_DETAILS = "Transaction Detail"
    const val STATUS = "Status"
    const val NOTIFICATION = "Notification"
    const val SUCCESS = "Success"
    const val FAILED = "Failed"
    const val SETUP = "Setup"
    const val SKIP = "Skip"
    const val CUSTOMER_REPORT = "Customer Report"

    // help section
    const val PLAY = "Play"
    const val CLOSE = "Close"
    const val PAUSED = "Paused"
    const val COMPLETED = "Completed"
    const val VIDEO = "Video"
    const val INAPPNOTIFICATION = "InAppNotification"

    const val CONTACT_US = "Contact Us Screen"

    // Referral
    const val REFERRAL = "Referral"

    // help interaction & method const values
    const val TEXT = "text"
    const val FEEDBACK = "Feedback"
    const val FEEDBACK_LIKE = "thumbs Up"
    const val FEEDBACK_UNLIKE = "thumbs Down"
    const val SHARE_FEEDBACK = "Share Feedback"
    const val SUBMIT_FEEDBACK = "Submit Feedback"
    const val EXPAND = "Open"
    const val COLLAPSE = "Closed"

    const val CARD = "Card"
    const val REGISTER = "Register"

    // Insurance
    const val INSURANCE = "Insurance"

    // Expense
    const val EXPENSE = "Expense"
    const val EXPENSE_TX = "Expense Tx"

    const val CASH_SALES = "Cash sales"
    const val CASH_SALE_TX = "Cash sale Tx"

    // Supplier Payments
    const val INVALID_ACCOUNT_NUMBER = "invalid_account_number"
    const val INVALID_IFSC = "invalid_ifsc"
    const val INVALID_NAME = "invalid_name"
    const val INVALID_ACCOUNT_OR_IFSC = "invalid_account_number_or_ifsc"
    const val INVALID_PAYMENT_ADDRESS = "invalid_payment_address"
    const val RELATIONSHIP = "Relationship"

    // Cashback
    const val FIRST = "First"
    const val REGULAR = "Regular"
    const val NOT_AVAILABLE = "NA"
    const val CUSTOMER_SYNC_STATUS = "customer_sync_status"
    const val DEFAULT_MODE = "Default Mode"

    // Kyc
    const val COMPLETE_KYC = "complete_kyc"
    const val KYC_STATUS = "kyc_status"
    const val KYC_BANNER_TYPE_INFO = "info_alert"
    const val KYC_BANNER_TYPE_LIMIT_REACHED = "limit_alert"
    const val YES = "yes"
    const val NO = "no"
}

object Screen {
    const val MERCHANT_DESTINATION_SCREEN = "Merchant Destination Screen"
    const val LINK_PAY_SCREEN = "Link Pay Screen"
    const val SUPPLIER_PAYMENT_DIALOG_SCREEN = "Supplier Payment Dialog Screen"
    const val QR_SCANNER_SCREEN = "QR Scanner Screen"
    const val RELATIONSHIP_REMINDER = "Relationship Reminder"
    const val CUSTOMER_SCREEN = "Customer Screen"
    const val SUPPLIER_SCREEN = "Supplier Screen"
    const val CUSTOMER_SCREEN_VOICE_TRANSACTION = "Customer Screen: Voice Transaction"
    const val DELETE_CUSTOMER = "Delete Customer"
    const val DELETE_SUPPLIER = "Delete Supplier"
    const val ADD_TRANSACTION_SHORTCUT = "Add Transaction Shortcut"
}

// Only for Mixpanel
object SuperProperties {
    const val INDIVIDUAL_ID = "individual_id"
    const val MERCHANT_ID = "merchant_id"
    const val LANG = "lang"
    const val OKCREDIT_VERTSION = "OkC Version"
    const val CUSTOMER_COUNT = "Accounts"
    const val CUSTOMER_TRANSACTION_COUNT = "Transactions"

    const val AAID = "AAID"
    const val UNSYNC_TRANSACTIONS_COUNT = "UnSync Transactions"
    const val UNSYNC_RELATIONSHIPS_COUNT = "unsync_add_relationships"
    const val IMMUTABLE_RELATIONSHIPS_COUNT = "customer_count_immutable"
    const val BUSINESS_COUNT = "business_count"
}

object IdentityProperties {
    const val MERCHANT_ID = "merchant_id"
    const val IDENTITY = "Identity"
}

object UserProperties {
    const val MERCHANT_ID = "merchant_id"
    const val NAME = "name"
    const val LANGUAGE = "language"
    const val LANGUAGE_DEVICE = "language_device"
    const val DEVICE_RAM = "Device RAM"
    const val DEVICE_INTERNAL_STORAGE = "Device Internal Storage"
    const val DEVICE_SYSTEM_STORAGE = "Device System Storage"
    const val DEVICE_CPU_CORES = "Device Cpu Cores"
    const val DEVICE_CPU_CLOCK_SPEED = "Device CPU Clock Speed"
    const val DEVICE_NETWORK_CONNECTIVITY_TYPE = "Network Connectivity Type"

    const val CUSTOMER_COUNT = "Customer Count"
    const val CUSTOMER_TRANSACTION_COUNT = "Transaction Count"
    const val MERCHANT_CATEGORY = "Merchant Category"
    const val INSTALL_SOURCE = "Install Source"

    const val ARE_NOTIFICATIONS_ENABLED = "Are Notifications Enabled"
    const val IS_IGNORING_BATTERY_OPTIMIZATIONS = "Is ignoring Battery Optimizations"
}
